TYPES = 7
PATTERNSIZE = 4
BOARDROWS = 20 + PATTERNSIZE
BOARDCOLS = 10

WINDOWWIDTH = 500
WINDOWHEIGHT = 700

BLANK = ' '

TYPE_L, TYPE_J, TYPE_I, TYPE_O, TYPE_T, TYPE_S, TYPE_Z = range(7)
DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_LEFT = range(4)
